rails_link: "https://www.railstutorial.org"
rails_contact_link: "https://www.railstutorial.org/contact"
rails_help_link: "https://www.railstutorial.org/help"
rails_book_link: "https://www.railstutorial.org/book"
rails_screencast_link: "http://screencasts.railstutorial.org/"
ruby_link: "http://rubyonrails.org/"
micheal_link: "http://www.michaelhartl.com/"
news_link: "http://news.railstutorial.org/"
